### ISSUE TITLE
Create A GUI Calculator Using TKinter

### ISSUE THREAD

**Issue by arun-jain-dev** [arun-jain-dev/Mini-Tkinter-Programs-Collection#2]

**Comment by aryashah2k** [comment]
Hi, I would love to work on a GUI Calculator Using TKinter. Do consider assigning this issue to me! Would love to work on this and refresh my knowledge for this framework!

**Comment by arun-jain-dev** [comment]
Hello, thanks for the interest, it is a relatively new repo and you are the very first contributor. You can surely start working on this. I have assigned this issue to you.
