### ISSUE TITLE
Add Documentation for Tkinter GUI Calculator

### ISSUE THREAD

**Issue by arun-jain-dev** [arun-jain-dev/Mini-Tkinter-Programs-Collection#4]

**Comment by aryashah2k** [comment]
Hi, I have been assigned the issue #2 and would like to create a proper documentation for the same. Please assign this issue of creating documentation for the GUI Calculator as well to me. thanks.

**Comment by arun-jain-dev** [comment]
Hello again, Yes sure, it is better if you handle the documentation as well since you are creating the rpoject as well. I am assigning this issue to you too.
