### ISSUE TITLE
Make the main repository README Intuitive and Well Organized.

### ISSUE THREAD

**Issue by aryashah2k** [arun-jain-dev/Mini-Tkinter-Programs-Collection#7]
I am currently working on two issues related to GUI Calculator, what I was asking for is if I could also help create a proper well organized readme for the main repository where I could organize projects in 3 categories - Beginner, intermediate and advance level. Within each section there could be a table of projects with their respective folder links! Do let me know what you think about this idea? @arun-jain-dev

**Comment by arun-jain-dev** [comment]
Quite a long time since i saw this, sure i would love to have contribs on this repo
